name: list_expandable
description: A new Flutter widget support expanded and collapsed list for user..
version: 0.0.1
author: Leo Vo
homepage: https://github.com/liemvo

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
